all: filter generator finish
filter: filter.cc
	g++ -Wall filter.cc -o filter
generator: generator.cc
	g++ -Wall generator.cc -o generator
finish: finish.cc
	g++ -Wall finish.cc -o finish
clean: filter generator finish
	rm filter generator finish
