#!/bin/bash

STATUS_PATH="https://www.spoj.pl/status/"

wget --no-check-certificate -q -O statuspage $STATUS_PATH
cat statuspage | # Pega o html 
	sed -e '706,968d' -e '1,176d' | # Deleta as linhas 1 a 30 e 64 a 78
	sed -e 's/<br>//g' |
	sed -e '/^[ \t]*$/d' | # Retira as linhas vazias
	sed -e 's/&nbsp;//g' | # Retira os espacos do html
	sed -e '/<td><a href="\/users\/[^"]*" title="/{s/">/\n/1}' | # Retira o id do autor da tag
	sed -e 's/<td><a href="\/users\/[^"]*" title="/ /g' | # cont. Retira o id do autor da tag
	sed -e '/<td><a href="\/problems\/[^"]*"  title="/{s/">/\n/g}' | # Retira o id da questao da tag
	sed -e 's/<td><a href="\/problems\/[^"]*"  title="/ /g' | # cont. Retira o id da questao da tag
	sed -e 's/<[^>]*>/\n/g' | # Retira todas tags e quebra
	sed -e '/^[ \t]*$/d' | # Retira as linhas vazias
	sed -e 's/^[ \t]*//' | # Retira os espacos no comeco de todas as linhas
	sed -e 's/[ \t]*$//' > tmp # Retira os espacos no final de todas as linhas

cat tmp |
	sed -n "/.*-.*-[0-9]* .*:.*:[0-9]*/p" |
	while read LINE;
	do
		AUX="s/$LINE/`date -d "$LINE" +%s`/g"
		#echo "> $AUX"
		sed -e "$AUX" tmp > tmp2
		cat tmp2 > tmp
	done

cat tmp

rm statuspage tmp tmp2
