all:
	$(MAKE) -C archive/
	$(MAKE) -C pku/
	$(MAKE) -C spoj/
	$(MAKE) -C ural/
	$(MAKE) -C uva/
clean:
	$(MAKE) clean -C archive/
	$(MAKE) clean -C pku/
	$(MAKE) clean -C spoj/
	$(MAKE) clean -C ural/
	$(MAKE) clean -C uva/
