#!/bin/bash

STATUS_PATH='http://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=19'

wget -q -O statuspage $STATUS_PATH
cat statuspage | # Pega o html 
	sed -e '780,836d' -e '1,226d' | # Deleta as linhas 1 a 30 e 64 a 78
	sed -e 's/&nbsp;/\n/g' | # Retira os espacos do html
	sed -e '/<a href="index.php?option=com_onlinejudge&amp;page=show_authorstats&amp;userid=/{s/>/\n/5}' | # Retira o id do autor da tag
	sed -e 's/<a href="index.php?option=com_onlinejudge&amp;page=show_authorstats&amp;userid=/ /g' | # cont. Retira o id do autor da tag
	sed -e 's/<[^>]*>/\n/g' | # Retira todas tags e quebra
    sed -e 's/-->/\n/g' |
    sed -e 's/">/\n/' |
	sed -e '/^[ \t]*$/d' | # Retira as linhas vazias
	sed -e 's/^[ \t]*//' | # Retira os espacos no comeco de todas as linhas
	sed -e 's/[ \t]*$//' | # Retira os espacos no final de todas as linhas
	sed -e '1,3d' > tmp # retira as 3 primeiras linhas
	
cat tmp |
	sed -n "/.*-.*-[0-9]* .*:.*:[0-9]*/p" |
	while read LINE;
	do
		AUX="s/$LINE/`date -d "$LINE" +%s`/g"
		#echo "> $AUX"
		sed -e "$AUX" tmp > tmp2
		cat tmp2 > tmp
	done

cat tmp

rm statuspage tmp tmp2
